language: generic
sudo: required
services:
  - docker

env:
  global:
    - LATEST=4.6.0
  matrix:
    - VERSION=4.6.0
    - VERSION=4.5.1
    - VERSION=4.4.5
    - VERSION=4.3.4
    - VERSION=4.2.2
    - VERSION=4.1.2
    - VERSION=4.0.5


install: true

before_script:
  - docker --version

script:
  - TAG_VERSION=${VERSION%.*}
  - docker build --build-arg MATTERMOST_VERSION=${VERSION} -t johannweging/mattermost:${TAG_VERSION} ./

before_deploy:
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

deploy:
  provider: script
  script: bash deploy.sh
  on:
    all_branches: true
